### ISSUE TITLE
No visible messages posted in real time chat, no cursor focus

### ISSUE THREAD

**Issue by FreeScholar** [FreeScholar/customchatServer#13]
When logged into the room in the Real Time chat mode, No messages posting in chat - no public and no private - using FireFox

Also - possibly related -
When logged in to the Manual chat mode, the cursor is not focused on the Express Public Message field.
see: http://chatalotchat.com:7000/jelly?1521173564231

**Comment by JamesVorder** [comment]
I'm going to pick this up this week; try to fix it.

**Comment by JamesVorder** [comment]
Get an alert box with the message `You have timed out of the room.  Hit Reload or Refresh on your browser to re-enter the chat.` whenever I open a real-time chat in FF.

**Comment by JamesVorder** [comment]
Live chat doesn't work at all in Chromium. In that browser, what appears to be a binary file just downloads infinitely. 
![InfiniteDownload](https://user-images.githubusercontent.com/5509670/54140806-ceaf7100-43fa-11e9-87d2-bee5cd0e0375.png)

**Comment by FreeScholar** [comment]
This looks great in FireFox! tested on port 7000 - the focus is fixed too. ++

**Comment by FreeScholar** [comment]
Same for me in Chromium browser. the chat pane is blank.

**Comment by JamesVorder** [comment]
> Same for me in Chromium browser. the chat pane is blank.

I'm going to close this issue, and move the chrome finding to the "Odd behavior in chrome" issue.
