### ISSUE TITLE
Fragile Directory Structure

### ISSUE THREAD

**Issue by JamesVorder** [FreeScholar/customchatServer#17]
When you make the JAR package, there is still more to remember when deploying. The html folder, ccLicense, and button.js all have to be placed in the same folder. It might be more ideal to have the whole thing packaged as a JAR file.

**Comment by JamesVorder** [comment]
In addition to the things above, it looks like JAR dependencies are living in a `lib/` directory, and are not just bundled into the project JAR.

**Comment by FreeScholar** [comment]
The reason for not bundling was that the path to the HTML folder and other functions can change by editing the xxxx.properties file. It is filled with things we never got to add a UI for.
